
SELECT 
    A.IDMOV, A.CODLOC, A.CODFILIAL, B.NOME AS FILIAL, 
    A.CODLOCENTREGA, C1.NOME AS LOCAL_ENTREGA,
    A.CODDEPARTAMENTO, C2.NOME AS DEPARTAMENTO, A.CODCFO, E.NOME AS CLIENTE,
    A.NUMEROMOV AS NF, A.CODTMV, F.desc_STATUS AS 'DESC_STATUS', 
    A.DATACRIACAO, A.DATAEMISSAO, A.VALORLIQUIDOORIG,
    A.CODUSUARIO,G.NOME AS 'GESTOR',A.RECMODIFIEDON, A.Historico, 
    A.CAMPOLIVRE1, A.DATAMOVIMENTO, A.DATACANCELAMENTOMOV, A.DATAEXTRA1

FROM CorporeRM.TMOV A

LEFT JOIN CorporeRM.GFILIAL B
    ON A.CODFILIAL = B.CODFILIAL

LEFT JOIN CorporeRM.GDEPTO C1
    ON A.CODLOCENTREGA COLLATE Latin1_General_CI_AS = C1.CODDEPARTAMENTO
    AND A.CODFILIAL = C1.CODFILIAL

LEFT JOIN CorporeRM.GDEPTO C2
    ON A.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = C2.CODDEPARTAMENTO
    AND A.CODFILIAL = C2.CODFILIAL

LEFT JOIN CorporeRM.FCFO E
    ON A.CODCFO COLLATE Latin1_General_CI_AI = E.CODCFO

LEFT JOIN FINANCA.dbo.descricao_STATUS F
	ON A.STATUS = F.STATUS

LEFT JOIN CorporeRM.TVEN G
	ON A.CODVEN1 = G.CODVEN
WHERE YEAR(A.DATAEMISSAO) = 2025 
  AND A.CODTMV = '2.2.14'

ORDER BY A.DATAEMISSAO DESC;
-- Fim da consulta
-- Data de criação: 2025-01-15