DECLARE @DT DATE = GETDATE();

SELECT DESCNVL1, DESCNVL2, DESCNVL3, DESCNVL4, DESCNVL5, DESCNVL6,
       COD_CONTA, RIGHT(CODGERENCIAL,16) AS CC, PROJETO, ACAO, UNIDADE,
       FORNECEDOR, COMPLEMENTO, CONTA_FECHAMENTO, DATA,
       UNIFICAVALOR AS VALOR
FROM FatoFechamento A
WHERE YEAR(DATA) = YEAR(@DT) AND TIPO = 'Despesa';
